### ISSUE TITLE
Doesn't work with Greasemonkey, only Tampermonkey.

### ISSUE THREAD

**Issue by Deliphin** [gauss256/redactle-utils#1]
If possible, this should be updated to work with greasemonkey as well.

On greasemonkey, literally nothing is changed, it's as if the script wasn't installed.

**Comment by gauss256** [comment]
@Deliphin ~~What browser were you using?~~ Never mind. I have reproduced it.

**Comment by gauss256** [comment]
Fixed in https://github.com/gauss256/redactle-utils/commit/8d4ae09952082c7f02cb099dda0a59c8a42fba09
